### ISSUE TITLE
Windows XP 报告 模板文件不存在

### ISSUE THREAD

**Issue by luoshupeng** [hanzhaoxin/ExcelReport#1]
Windows XP 报告 模板文件不存在
![default](https://cloud.githubusercontent.com/assets/883086/7630820/ecd4808e-fa6c-11e4-9122-a2335b5c659b.png)

**Comment by hanzhaoxin** [comment]
请检查模板文件是否在指定目录下存在。

**Comment by luoshupeng** [comment]
模板文件确认是存在于指定目录下

**Comment by luoshupeng** [comment]
这个已经试过了，XML和模板文件都需要绝对路径

**Comment by hanzhaoxin** [comment]
.
