### ISSUE TITLE
使用xlsx作为模板时，会发生使用未关闭的流异常

### ISSUE THREAD

**Issue by luoshupeng** [hanzhaoxin/ExcelReport#2]
使用xlsx作为模板时，会发生使用未关闭的流异常

**Comment by JsonRuby** [comment]
是有这个问题.mark一下就好了
  //ms.Flush();
 //ms.Position = 0;

**Comment by hanzhaoxin** [comment]
@JsonRuby 你可以提交代码的，已便记录对项目的贡献。

**Comment by JsonRuby** [comment]
@hanzhaoxin OK.下次有机会再pull request :)
