### ISSUE TITLE
新需求?

### ISSUE THREAD

**Issue by JsonRuby** [hanzhaoxin/ExcelReport#3]
如果一个sheet里,有页头,OK用cell+part.

接下来是表体,list<T>.OK用table.
那问题来了.如果这时候我还有页脚.
其中又有parameter.这时候就不能正确format了.
因为记录到页脚parameter的point都是旧的.(list 行数未知)

这个问题可能也很常见.可以考虑扩展一下.

**Comment by hanzhaoxin** [comment]
不是新需求。ExcelReport中存在处理这个问题的机制。

**Comment by hanzhaoxin** [comment]
.
