### ISSUE TITLE
Nuget 依赖项错误

### ISSUE THREAD

**Issue by Nokecy** [hanzhaoxin/ExcelReport#8]

**Comment by hanzhaoxin** [comment]
打包环境：vs2017  + NETStandard2

**Comment by Nokecy** [comment]
![image](https://user-images.githubusercontent.com/12318131/54245728-f6264b00-456c-11e9-9ac1-7961a1496f1f.png)

**Comment by Nokecy** [comment]
应该是有依赖项的吧
